### ISSUE TITLE
CSS not updating

### ISSUE THREAD

**Issue by edge0701** [meteorwebcomponents/synthesis#12]
Often, when changing styles in a component's CSS file, changes are not propogated into the application. I am not sure of the mechanics of Meteor so cannot investigate further. My only resolution is to delete the .meteor/local directory and restart Meteor, but this is painful.

**Comment by aruntk** [comment]
@edge0701 I'm aware of this issue. This happens because I'm replacing css link tags with style tag(with content of the css file inside the tag. This is to enable the polymer style scope). Because of meteor's file cache mechanism if you change the css file alone final result wont change(since the html/js files are unchanged). A workaround for now is to include css inside the html file itself. I'll try to figure out a way to solve this issue.

**Comment by edge0701** [comment]
Thanks for such a speedy reply. I will use this method for development before putting the contents in the CSS file and rebuilding.
Otherwise, great work. Donate button?

**Comment by aruntk** [comment]
Thanks for the appreciation. [My paypal page](https://www.paypal.me/arunkumartk) . I've never used paypal to receive money. Sorry if the link doesn't work. :)

**Comment by edge0701** [comment]
The link works, but trying to send anything I get "This recipient is currently unable to receive money."
Let me know when you have the PayPal/donate issue working. Also, please hit me up on gmail, email is the same as my github username @gmail.com, saves me spamming this issues section, and I'll probably need your help again in the future. I'm sure you're a busy chap but I'd appreciate it, and I will recompense you (: Thank you!

**Comment by aruntk** [comment]
Sure . :) . I'm closing the issue. Feel free to reopen if needed.
