### ISSUE TITLE
Use npm instead of bower

### ISSUE THREAD

**Issue by gbisheimer** [meteorwebcomponents/synthesis#5]
Hi there. Nice work!!! 

As Polymer is [making the switch](https://github.com/Polymer/polymer/issues/326) to npm and Meteor 1.3 supports it, ¿may you consider to make switch in this project too?

Just because instead of doing `npm install && meteor` to run a project, we need to `npm install && bower install && meteor`.

**Comment by aruntk** [comment]
@gbisheimer Certainly. If polymer makes a switch to npm we switch. But I'm not sure how to import static contents from node_modules directory. I don't think this will work in the straight forward way import "@polymer/paper-input/paper-input.html";  because the html compiler wont be able to access files inside node_modules directory;

**Comment by AndreasGalster** [comment]
Wouldn't it make sense to already start looking into this now? It seems the Polymer team is almost 100% focusing on having a beta/production ready CLI ready for Google IO and afaik the NPM migration/support is planned after this, so work on that will begin shortly.

Build times with bower are painstakingly slow at this point, one file change takes 1+ minute to rebuild.

**Comment by aruntk** [comment]
@AndreasGalster Even if we get a stable usable version of polymer in npm I'm not sure how to import static files from node_modules in meteor during building. Ideas are welcome. Build time is slow because this issue is still unsolved. https://github.com/meteor/meteor/issues/6859 . Build time depends on this issue only. It has nothing to do with synthesis. You can verify this by deleting js files from imports directory. For now what you can do is delete unnecessary js files from bower_components and to keep that copy of bower_components. Find out which package is adding these js files. Unfortunately this is the only way right now as we cannot replace the ecmascript package with something else. 
I'm not sure why every file change is resulting in delay because in my experience only the first build time takes time. Since they use caching individual file changes are very fast.

**Comment by AndreasGalster** [comment]
Oh sorry, I might have misunderstood the issue. I thought that having the components in the node_modules folder would fix the build issues. I haven't tried importing html files yet but this should perhaps be possible. They already fixed that for CSS/SCSS files. Not sure if you've done some tests yet. If not I'll test something.

**Comment by aruntk** [comment]
@AndreasGalster As of now there is no way to get static files(or I'm not aware of one yet) which are in  node_modules during building. Synthesis is a static html compiler plugin which splits html files into 3 sections head,body and js(anything inside script tag). So we need to get file contents during building.  check this issue . https://github.com/meteor/meteor/issues/6098

**Comment by aruntk** [comment]
@gbisheimer , @AndreasGalster . Guys here is a demo of meteor + polymer using npm and synthesis. :).  https://github.com/meteorwebcomponents/synthesis-meteor-polymer-npm-demo

**Comment by dandv** [comment]
[+1](https://pinboard.in/search/u:dandv?query=against+bower)
